name: CI CalculatirDSCJH

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Se configura JDK 24 (Temurin)
        uses: action/setup-java@v5
        with:
          distribution: temurin
          java-version: "24"
          check-latest: true
          cache: gradle

      - name: Asegura qu gradlew sea ejecutable
        run: chmod +x ./gradlew
      - name: Compilación
        run: ./gradlew compileJava -no-daemon

